apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://10.161.118.219:6379
    isDefault: false
    editable: true
    jsonData:
      client: standalone

dashboards:
  - name: 'Trading System'
    type: 'file'
    options:
      path: '/var/lib/grafana/dashboards/trading-dashboard.json'
