import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const tierColors = ['bg-brand-accent-blue/20', 'bg-brand-accent-purple/20', 'bg-brand-accent-green/20'];
const CommunityLeaderboard = ({ entries, loading = false }) => {
    return (_jsxs("section", { className: "relative overflow-hidden rounded-4xl border border-white/10 bg-brand-abyss/80 p-6 shadow-sapphire-lg", children: [_jsx("div", { className: "absolute inset-0 bg-[radial-gradient(circle_at_top,_rgba(59,130,246,0.18),_transparent_70%)]" }), _jsxs("div", { className: "relative space-y-6", children: [_jsx("header", { className: "flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between", children: _jsxs("div", { children: [_jsx("p", { className: "text-xs uppercase tracking-[0.35em] text-brand-ice/70", children: "Community Hall" }), _jsx("h3", { className: "mt-2 text-2xl font-semibold text-white", children: "Top Sapphire Contributors" }), _jsx("p", { className: "mt-2 text-sm text-brand-ice/80", children: "Points accrue for daily check-ins, insightful comments, and sentiment votes. Bots can reference this leaderboard for credible crowd signals without over-weighting them." })] }) }), loading ? (_jsx("div", { className: "space-y-3", children: Array.from({ length: 5 }).map((_, index) => (_jsx("div", { className: "h-16 animate-pulse rounded-3xl border border-white/10 bg-white/5" }, `leaderboard-skeleton-${index}`))) })) : entries.length === 0 ? (_jsx("div", { className: "rounded-3xl border border-white/10 bg-white/5 px-5 py-6 text-center text-sm text-brand-ice/70", children: "Crowd pilots are just getting started. Check in, vote, and leave feedback to climb the leaderboard." })) : (_jsx("ul", { className: "space-y-3", children: entries.map((entry, index) => {
                            const tierColor = tierColors[index] ?? 'bg-white/5';
                            return (_jsx("li", { className: `relative overflow-hidden rounded-3xl border border-white/10 px-5 py-4 shadow-sapphire ${tierColor}`, children: _jsxs("div", { className: "relative flex items-center gap-4", children: [_jsxs("div", { className: "flex h-12 w-12 flex-none items-center justify-center rounded-full bg-black/30 text-lg font-semibold text-white", children: ["#", index + 1] }), _jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-2", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-white", children: entry.displayName }), _jsx("p", { className: "text-xs text-brand-ice/60", children: entry.publicId })] }), _jsxs("div", { className: "text-right", children: [_jsxs("p", { className: "text-lg font-semibold text-brand-accent-green", children: [entry.points.toLocaleString(), " pts"] }), entry.lastActive && (_jsxs("p", { className: "text-xs text-brand-ice/60", children: ["Active ", new Date(entry.lastActive).toLocaleDateString()] }))] })] }), _jsxs("div", { className: "mt-3 grid grid-cols-3 gap-3 text-xs text-brand-ice/70", children: [_jsxs("div", { className: "rounded-2xl border border-white/10 bg-white/5 px-3 py-2 text-center", children: [_jsx("p", { className: "font-semibold text-white", children: entry.checkIns ?? 0 }), _jsx("p", { children: "Check-ins" })] }), _jsxs("div", { className: "rounded-2xl border border-white/10 bg-white/5 px-3 py-2 text-center", children: [_jsx("p", { className: "font-semibold text-white", children: entry.votes ?? 0 }), _jsx("p", { children: "Votes" })] }), _jsxs("div", { className: "rounded-2xl border border-white/10 bg-white/5 px-3 py-2 text-center", children: [_jsx("p", { className: "font-semibold text-white", children: entry.comments ?? 0 }), _jsx("p", { children: "Comments" })] })] })] })] }) }, entry.publicId));
                        }) }))] })] }));
};
export default CommunityLeaderboard;
