import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const StatusCard = ({ health, loading }) => {
    if (loading || !health) {
        return (_jsxs("div", { className: "sapphire-panel p-6 text-center text-brand-muted", role: "status", "aria-live": "polite", "aria-busy": "true", children: [_jsx("span", { className: "sr-only", children: "Loading status..." }), _jsxs("div", { className: "animate-pulse space-y-3", children: [_jsx("div", { className: "mx-auto h-10 w-10 rounded-full bg-brand-border/60" }), _jsx("p", { className: "text-sm", children: "Calibrating systems\u2026" })] })] }));
    }
    const statusBadge = health.running ? 'bg-accent-emerald/85 text-brand-midnight' : 'bg-warning-amber/85 text-brand-midnight';
    return (_jsxs("div", { className: "sapphire-panel p-6 text-brand-muted", children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs uppercase tracking-[0.3em] text-brand-muted/80", children: "System Status" }), _jsx("h3", { className: "mt-2 text-2xl font-semibold text-brand-ice", children: health.running ? 'Operational' : 'Standby' }), _jsx("p", { className: "mt-2 text-sm text-brand-muted", children: health.running
                                    ? 'Autonomous execution enabled · risk guardrails engaged'
                                    : 'Trader halted · awaiting operator command' })] }), _jsxs("span", { className: `inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-semibold ${statusBadge}`, children: [_jsx("span", { className: "h-2 w-2 rounded-full bg-brand-midnight" }), health.running ? 'Live' : 'Paused'] })] }), _jsxs("div", { className: "mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2", children: [_jsxs("div", { className: "relative overflow-hidden rounded-xl border border-brand-border/60 bg-brand-abyss/75 p-4 text-xs text-brand-muted shadow-sapphire", children: [_jsx("p", { className: "text-[0.65rem] uppercase tracking-[0.3em] text-brand-muted/70", children: "Mode" }), _jsx("p", { className: "mt-2 text-base font-medium text-brand-ice", children: health.paper_trading ? 'Paper Trading' : 'Live Execution' }), _jsx("p", { className: "mt-1", children: health.paper_trading
                                    ? 'Synthetic orders for signal QA'
                                    : 'Orders routed to orchestrator' })] }), _jsxs("div", { className: "relative overflow-hidden rounded-xl border border-brand-border/60 bg-brand-abyss/75 p-4 text-xs text-brand-muted shadow-sapphire", children: [_jsx("p", { className: "text-[0.65rem] uppercase tracking-[0.3em] text-brand-muted/70", children: "Diagnostics" }), _jsx("p", { className: "mt-2 text-base font-medium text-brand-ice", children: health.last_error ? 'Attention Required' : 'Nominal' }), _jsx("p", { className: "mt-1", children: health.last_error ?? 'No critical alerts in the last hour.' })] })] }), _jsxs("div", { className: "mt-4", children: [_jsx("h4", { className: "text-xs font-semibold uppercase tracking-wider text-brand-muted/80", children: "System Controls" }), _jsx("p", { className: "mt-1 text-xs text-brand-muted/70", children: "Operator controls are disabled for public viewing to ensure system integrity." })] })] }));
};
export default StatusCard;
