import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const StatusCard = ({ health, loading }) => {
    if (loading || !health) {
        return (_jsx("div", { className: "rounded-2xl border border-surface-200/40 bg-surface-100/60 p-6 text-center text-slate-300 shadow-glass", children: _jsxs("div", { className: "animate-pulse space-y-3", children: [_jsx("div", { className: "mx-auto h-10 w-10 rounded-full bg-slate-600/40" }), _jsx("p", { className: "text-sm", children: "Calibrating systems\u2026" })] }) }));
    }
    const statusBadge = health.running ? 'bg-emerald-400/80 text-slate-900' : 'bg-amber-400/80 text-slate-900';
    return (_jsxs("div", { className: "rounded-2xl border border-surface-200/40 bg-surface-100/80 p-6 text-slate-200 shadow-glass", children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs uppercase tracking-[0.3em] text-slate-400", children: "System Status" }), _jsx("h3", { className: "mt-2 text-2xl font-semibold text-white", children: health.running ? 'Operational' : 'Standby' }), _jsx("p", { className: "mt-2 text-sm text-slate-400", children: health.running
                                    ? 'Autonomous execution enabled · risk guardrails engaged'
                                    : 'Trader halted · awaiting operator command' })] }), _jsxs("span", { className: `inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-semibold ${statusBadge}`, children: [_jsx("span", { className: "h-2 w-2 rounded-full bg-slate-900" }), health.running ? 'Live' : 'Paused'] })] }), _jsxs("div", { className: "mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2", children: [_jsxs("div", { className: "rounded-xl border border-surface-200/50 bg-surface-50/40 p-4 text-xs text-slate-300", children: [_jsx("p", { className: "text-[0.65rem] uppercase tracking-[0.3em] text-slate-500", children: "Mode" }), _jsx("p", { className: "mt-2 text-base font-medium text-white", children: health.paper_trading ? 'Paper Trading' : 'Live Execution' }), _jsx("p", { className: "mt-1 text-slate-400", children: health.paper_trading
                                    ? 'Synthetic orders for signal QA'
                                    : 'Orders routed to orchestrator' })] }), _jsxs("div", { className: "rounded-xl border border-surface-200/50 bg-surface-50/40 p-4 text-xs text-slate-300", children: [_jsx("p", { className: "text-[0.65rem] uppercase tracking-[0.3em] text-slate-500", children: "Diagnostics" }), _jsx("p", { className: "mt-2 text-base font-medium text-white", children: health.last_error ? 'Attention Required' : 'Nominal' }), _jsx("p", { className: "mt-1 text-slate-400", children: health.last_error ?? 'No critical alerts in the last hour.' })] })] })] }));
};
export default StatusCard;
