steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/trading-dashboard:latest', '--build-arg', 'VITE_API_URL=https://sapphire-trader-s77j6bxyra-nn.a.run.app', 'trading-dashboard']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/trading-dashboard:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'trading-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/trading-dashboard:latest'
      - '--region'
      - 'northamerica-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
images:
  - 'gcr.io/$PROJECT_ID/trading-dashboard:latest'
