steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/cloud-trader:backend', '-f', 'Dockerfile.backend', '.']
images:
  - 'gcr.io/${PROJECT_ID}/cloud-trader:backend'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
