apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: freqtrade-hpa
  namespace: trading
  labels:
    app: freqtrade-hft
    component: hft-framework
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: freqtrade-hft-bot
  minReplicas: 1
  maxReplicas: 2  # Limited to stay within budget
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Max
