# This file defines the node pools for the GKE cluster.
# For optimal latency, ensure that the region specified in your GKE cluster
# configuration matches the region of the Aster DEX API endpoint.

apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: standard-pool
spec:
  clusterRef:
    name: aiaister-cluster # Replace with your cluster name
  location: us-central1 # Ensure this matches the DEX region
  nodeConfig:
    machineType: n1-standard-4
    diskSizeGb: 100
  autoscaling:
    minNodeCount: 2
    maxNodeCount: 5
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: hft-pool
spec:
  clusterRef:
    name: aiaister-cluster # Replace with your cluster name
  location: us-central1 # Ensure this matches the DEX region
  nodeConfig:
    machineType: n1-highcpu-8
    diskSizeGb: 50
    taints:
    - key: hft-workload
      value: "true"
      effect: NoSchedule
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 3
