apiVersion: v1
kind: Service
metadata:
  name: coordinator-service
  namespace: trading-system-clean
  labels:
    app: mcp-coordinator
    component: messaging
spec:
  selector:
    app: mcp-coordinator
    component: messaging
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
