apiVersion: v1
kind: Secret
metadata:
  name: cloud-trader-secrets
  namespace: trading
type: Opaque
data:
  # Base64 encode real values: echo -n "your_real_value" | base64
  ASTER_API_KEY: ZHVtbXlfYXN0ZXJfYXBpX2tleQ==  # dummy_aster_api_key
  ASTER_SECRET_KEY: ZHVtbXlfYXN0ZXJfc2VjcmV0X2tleQ==  # dummy_aster_secret_key
  TELEGRAM_BOT_TOKEN: ZHVtbXlfdGVsZWdyYW1fYm90X3Rva2Vu  # dummy_telegram_bot_token
  TELEGRAM_CHAT_ID: ZHVtbXlfdGVsZWdyYW1fY2hhdF9pZA==  # dummy_telegram_chat_id
  GROK4_API_KEY: eGFpLWYyazJuNDNMaEtib2RLZ3JVclZTSWlrVDBkcGVNV21Nb0xHV0JacXZXUUdJSVhDRjZCaDdaT2J1R3FLQ3d0eUdyZGo5dDhLZW1XSXlVdmt5
  GEMINI_API_KEY: ZHVtbXlfZ2VtaW5pX2FwaV9rZXk=  # dummy_gemini_api_key
