apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hummingbot-hpa
  namespace: trading
  labels:
    app: hummingbot-mm
    component: hft-framework
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hummingbot-market-maker
  minReplicas: 1
  maxReplicas: 1  # Keep at 1 to maintain budget (already CPU-efficient)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # Slower scale-down for stability
      policies:
      - type: Percent
        value: 100  # Scale to 0 if needed
        periodSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
