apiVersion: v1
kind: Service
metadata:
  name: freqtrade-service
  namespace: trading
  labels:
    app: freqtrade-hft
    component: hft-framework
spec:
  selector:
    app: freqtrade-hft
    component: hft-framework
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
