apiVersion: v1
kind: Service
metadata:
  name: cloud-trader-service
  namespace: trading
spec:
  selector:
    app: cloud-trader
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-system-cloud-trader
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-trader
  template:
    metadata:
      labels:
        app: cloud-trader
    spec:
      containers:
      - name: cloud-trader
        image: us-central1-docker.pkg.dev/sapphireinfinite/cloud-run-source-deploy/cloud-trader:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-secret
              key: bot_token
        - name: TELEGRAM_CHAT_ID
          valueFrom:
            secretKeyRef:
              name: telegram-secret
              key: chat_id
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-coordinator-service
  namespace: trading
spec:
  selector:
    app: mcp-coordinator
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-system-mcp-coordinator
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-coordinator
  template:
    metadata:
      labels:
        app: mcp-coordinator
    spec:
      containers:
      - name: mcp-coordinator
        image: us-central1-docker.pkg.dev/sapphireinfinite/cloud-run-source-deploy/cloud-trader:latest
        ports:
        - containerPort: 8081
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: SERVICE_TYPE
          value: "mcp-coordinator"
        command: ["python", "-m", "uvicorn", "cloud_trader.api:app", "--host", "0.0.0.0", "--port", "8081"]
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi