#!/bin/bash
# Script to update DNS records for Firebase domain verification
# This is a helper script - actual DNS updates must be done in your DNS provider's control panel

echo "🔐 Firebase Domain Verification DNS Update"
echo "=========================================="
echo ""
echo "Domain: sapphiretrade.xyz"
echo ""
echo "📋 Current DNS TXT Records:"
dig TXT sapphiretrade.xyz +short 2>/dev/null | grep -E "hosting-site" || echo "  No hosting-site records found"
echo ""
echo "✅ Required DNS Changes:"
echo ""
echo "1. ADD this TXT record:"
echo "   Record type: TXT"
echo "   Domain name: sapphiretrade.xyz"
echo "   Value: hosting-site=sapphire-trading"
echo ""
echo "2. REMOVE this TXT record (if it exists):"
echo "   Record type: TXT"
echo "   Domain name: sapphiretrade.xyz"
echo "   Value: hosting-site=sapphiretrade"
echo ""
echo "📝 Next Steps:"
echo "   1. Log into your DNS provider's control panel"
echo "   2. Find the DNS management section for sapphiretrade.xyz"
echo "   3. Add the new TXT record (hosting-site=sapphire-trading)"
echo "   4. Remove the old TXT record (hosting-site=sapphiretrade) if it exists"
echo "   5. Wait 5-10 minutes for DNS propagation"
echo "   6. Return to Firebase and click 'Verify'"
echo ""
echo "🌐 Common DNS Providers:"
echo "   - Google Domains / Google Cloud DNS"
echo "   - Cloudflare"
echo "   - AWS Route 53"
echo "   - Namecheap"
echo "   - GoDaddy"
echo ""
echo "💡 After updating, verify with:"
echo "   dig TXT sapphiretrade.xyz +short"
