combiner: OR
displayName: "Sapphire Trade - Cloud Build Failures"
documentation:
  content: "Cloud Build jobs are failing. Check build logs for errors and CI pipeline issues."
  mimeType: text/markdown
conditions:
  - displayName: "Cloud Build job failed"
    conditionThreshold:
      filter: |
        resource.type = "build"
        AND metric.type = "cloudbuild.googleapis.com/builds/status"
        AND metric.labels.status = "FAILURE"
      aggregations:
        - alignmentPeriod: 300s
          crossSeriesReducer: REDUCE_COUNT
          groupByFields: []
          perSeriesAligner: ALIGN_COUNT
      comparison: COMPARISON_GT
      duration: 60s
      thresholdValue: 0
      trigger:
        count: 1
enabled: true
notificationChannels: []
