combiner: OR
displayName: "Sapphire Trade - Cloud Run Revision Failures"
documentation:
  content: "Cloud Run service revisions are failing to start. Check logs for container startup errors."
  mimeType: text/markdown
conditions:
  - displayName: "Cloud Run revision failed"
    conditionThreshold:
      filter: |
        resource.type = "cloud_run_revision"
        AND metric.type = "run.googleapis.com/container/startup_latencies"
        AND metric.labels.state = "failed"
      aggregations:
        - alignmentPeriod: 300s
          crossSeriesReducer: REDUCE_COUNT
          groupByFields: []
          perSeriesAligner: ALIGN_COUNT
      comparison: COMPARISON_GT
      duration: 60s
      thresholdValue: 0
      trigger:
        count: 1
enabled: true
notificationChannels: []
