steps:
  # Build the cloud-trader service container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cloud-trader:latest'
      - '.'

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cloud-trader:latest'

  # Deploy to Cloud Run 
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cloud-trader'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cloud-trader:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--cpu-boost'
      - '--no-cpu-throttling'
      - '--set-env-vars'
      - 'ENABLE_PAPER_TRADING=false,ORCHESTRATOR_URL=https://api.sapphiretrade.xyz/orchestrator,MCP_URL=https://api.sapphiretrade.xyz/mcp,MCP_SESSION_ID=sapphire-trading-session'
      - '--update-secrets'
      - 'ASTER_API_KEY=ASTER_API_KEY:latest,ASTER_SECRET_KEY=ASTER_SECRET_KEY:latest,TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN:latest,TELEGRAM_CHAT_ID=TELEGRAM_CHAT_ID:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'
