apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: trading-system-alerts
  namespace: trading
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
  - name: trading-system
    rules:
    - alert: TradingSystemDown
      expr: up{job="cloud-trader"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Trading system is down"
        description: "The main trading service has been down for more than 5 minutes."

    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5..", job="cloud-trader"}[5m]) / rate(http_requests_total{job="cloud-trader"}[5m]) > 0.05
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value | printf \"%.2f\" }}% over the last 5 minutes."

    - alert: CircuitBreakerOpen
      expr: circuit_breaker_state{state="open"} == 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Circuit breaker opened"
        description: "Circuit breaker {{ $labels.name }} has opened due to failures."

    - alert: AgentUnhealthy
      expr: agent_health_status == 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Agent health issue"
        description: "Agent {{ $labels.agent }} is reporting unhealthy status."

    - alert: HighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="cloud-trader"}[5m])) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High request latency"
        description: "95th percentile latency is {{ $value | printf \"%.2f\" }}s."

    - alert: LowPortfolioPerformance
      expr: portfolio_daily_return < -0.05
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Significant portfolio loss"
        description: "Portfolio has lost {{ $value | printf \"%.2f\" }}% in the last period."

    - alert: HighMemoryUsage
      expr: container_memory_usage_bytes{pod=~"trading-.*"} / container_spec_memory_limit_bytes > 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage"
        description: "Pod {{ $labels.pod }} memory usage is {{ $value | printf \"%.1f\" }}%."

    - alert: DataCollectionLag
      expr: time() - data_collection_last_timestamp > 300
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Data collection lag"
        description: "Data collection is lagging by more than 5 minutes."

    - alert: BigQueryExportFailure
      expr: increase(bigquery_export_errors_total[5m]) > 0
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "BigQuery export failure"
        description: "{{ $value }} BigQuery export failures in the last 5 minutes."
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trading-system-monitor
  namespace: trading
  labels:
    team: trading
spec:
  selector:
    matchLabels:
      app: cloud-trader
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
  - port: health
    path: /healthz
    interval: 30s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: trading
  labels:
    grafana_dashboard: "1"
data:
  trading-overview.json: |
    {
      "dashboard": {
        "title": "Trading System Overview",
        "tags": ["trading", "overview"],
        "timezone": "browser",
        "panels": [
          {
            "title": "Portfolio Value",
            "type": "stat",
            "targets": [
              {
                "expr": "portfolio_value",
                "legendFormat": "Portfolio Value"
              }
            ]
          },
          {
            "title": "Agent Activity",
            "type": "bargauge",
            "targets": [
              {
                "expr": "agent_activity_score",
                "legendFormat": "{{ agent }}"
              }
            ]
          },
          {
            "title": "System Health",
            "type": "table",
            "targets": [
              {
                "expr": "up{job=~\"trading-.*\"}",
                "legendFormat": "{{ job }}"
              }
            ]
          },
          {
            "title": "Trading Signals",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(trading_signals_total[5m])",
                "legendFormat": "Signals/min"
              }
            ]
          },
          {
            "title": "Circuit Breaker Status",
            "type": "table",
            "targets": [
              {
                "expr": "circuit_breaker_state",
                "legendFormat": "{{ name }}"
              }
            ]
          },
          {
            "title": "Error Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total{status=~\"5..\"}[5m]) / rate(http_requests_total[5m]) * 100",
                "legendFormat": "Error Rate %"
              }
            ]
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }
  agent-performance.json: |
    {
      "dashboard": {
        "title": "Agent Performance Analysis",
        "tags": ["trading", "agents", "performance"],
        "timezone": "browser",
        "panels": [
          {
            "title": "Agent Win Rates",
            "type": "bargauge",
            "targets": [
              {
                "expr": "agent_win_rate",
                "legendFormat": "{{ agent }}"
              }
            ]
          },
          {
            "title": "Agent Profit/Loss",
            "type": "graph",
            "targets": [
              {
                "expr": "agent_pnl_total",
                "legendFormat": "{{ agent }}"
              }
            ]
          },
          {
            "title": "Agent Activity Over Time",
            "type": "heatmap",
            "targets": [
              {
                "expr": "increase(agent_activity_count[1h])",
                "legendFormat": "{{ agent }}"
              }
            ]
          },
          {
            "title": "Agent Decision Confidence",
            "type": "graph",
            "targets": [
              {
                "expr": "agent_decision_confidence",
                "legendFormat": "{{ agent }}"
              }
            ]
          }
        ],
        "time": {
          "from": "now-24h",
          "to": "now"
        },
        "refresh": "5m"
      }
    }
  system-reliability.json: |
    {
      "dashboard": {
        "title": "System Reliability & Resilience",
        "tags": ["trading", "reliability", "monitoring"],
        "timezone": "browser",
        "panels": [
          {
            "title": "System Uptime",
            "type": "stat",
            "targets": [
              {
                "expr": "up{job=~\"trading-.*\"} * 100",
                "legendFormat": "{{ job }}"
              }
            ]
          },
          {
            "title": "Circuit Breaker Status",
            "type": "table",
            "targets": [
              {
                "expr": "circuit_breaker_state",
                "legendFormat": "{{ name }}"
              }
            ]
          },
          {
            "title": "Health Check Results",
            "type": "table",
            "targets": [
              {
                "expr": "health_check_status",
                "legendFormat": "{{ check }}"
              }
            ]
          },
          {
            "title": "Recovery Actions",
            "type": "logs",
            "targets": [
              {
                "expr": "{job=\"auto-recovery\"}",
                "legendFormat": "Recovery Events"
              }
            ]
          },
          {
            "title": "Error Rate by Component",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(error_total{job=~\"trading-.*\"}[5m])",
                "legendFormat": "{{ job }}"
              }
            ]
          }
        ],
        "time": {
          "from": "now-6h",
          "to": "now"
        },
        "refresh": "1m"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: trading
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'alerts@sapphiretrading.com'
      smtp_auth_username: 'alerts@sapphiretrading.com'
      smtp_auth_password: 'your-app-password'

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'trading-team'
      routes:
      - match:
          severity: critical
        receiver: 'trading-team-critical'

    receivers:
    - name: 'trading-team'
      email_configs:
      - to: 'trading-team@sapphiretrading.com'
        subject: '[{{ .GroupLabels.alertname }}] Trading System Alert'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

    - name: 'trading-team-critical'
      email_configs:
      - to: 'trading-critical@sapphiretrading.com'
      pagerduty_configs:
      - service_key: 'your-pagerduty-key'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
  namespace: trading
  labels:
    app: prometheus-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-adapter
  template:
    metadata:
      labels:
        app: prometheus-adapter
    spec:
      containers:
      - name: prometheus-adapter
        image: directxman12/k8s-prometheus-adapter:v0.10.0
        args:
        - --cert-dir=/var/run/serving-cert
        - --config=/etc/adapter/config.yaml
        - --logtostderr=true
        - --metrics-relist-interval=30s
        - --prometheus-url=http://prometheus-k8s.monitoring.svc.cluster.local:9090
        - --secure-port=6443
        ports:
        - containerPort: 6443
        volumeMounts:
        - name: config
          mountPath: /etc/adapter
        - name: tmp
          mountPath: /tmp
        - name: certs
          mountPath: /var/run/serving-cert
      volumes:
      - name: config
        configMap:
          name: prometheus-adapter-config
      - name: tmp
        emptyDir: {}
      - name: certs
        secret:
          secretName: prometheus-adapter-tls
