apiVersion: v1
kind: Secret
metadata:
  name: cloud-trader-secrets
  namespace: trading-system-clean
type: Opaque
data:
  # Base64 encode real values: echo -n "your_real_value" | base64
  # Example: echo -n "your_api_key_here" | base64
  # IMPORTANT: Replace all placeholder values with your actual base64-encoded secrets
  ASTER_API_KEY: "PLACEHOLDER_ASTER_API_KEY_BASE64"  # Replace with actual base64-encoded API key
  ASTER_SECRET_KEY: "PLACEHOLDER_ASTER_SECRET_KEY_BASE64"  # Replace with actual base64-encoded secret
  TELEGRAM_BOT_TOKEN: "PLACEHOLDER_TELEGRAM_BOT_TOKEN_BASE64"  # Replace with actual base64-encoded bot token
  TELEGRAM_CHAT_ID: "PLACEHOLDER_TELEGRAM_CHAT_ID_BASE64"  # Replace with actual base64-encoded chat ID
  GROK4_API_KEY: "PLACEHOLDER_GROK4_API_KEY_BASE64"  # Replace with actual base64-encoded Grok API key
  GEMINI_API_KEY: "PLACEHOLDER_GEMINI_API_KEY_BASE64"  # Replace with actual base64-encoded Gemini API key
