import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
const Sidebar = ({ tabs, activeTab, onSelect, mobileMenuOpen, setMobileMenuOpen }) => {
    const handleTabSelect = (id) => {
        onSelect(id);
        if (setMobileMenuOpen) {
            setMobileMenuOpen(false);
        }
    };
    return (_jsxs(_Fragment, { children: [mobileMenuOpen && (_jsx("div", { className: "fixed inset-0 z-50 bg-black/50 backdrop-blur-sm lg:hidden", onClick: () => setMobileMenuOpen?.(false) })), _jsxs("aside", { className: `fixed lg:static top-0 left-0 z-50 h-full w-64 flex-col gap-6 bg-gradient-to-b from-surface-100/95 via-surface-100/90 to-surface-100/95 border-r border-surface-200/60 backdrop-blur-sm p-6 transition-transform duration-300 lg:translate-x-0 ${mobileMenuOpen ? 'translate-x-0' : '-translate-x-full lg:flex'}`, children: [_jsx("div", { className: "absolute top-0 right-0 h-32 w-32 rounded-full bg-gradient-to-br from-primary-400/10 to-accent-teal/10 blur-2xl" }), _jsx("div", { className: "absolute bottom-0 left-0 h-24 w-24 rounded-full bg-gradient-to-br from-accent-teal/10 to-primary-400/10 blur-xl" }), _jsxs("div", { className: "relative flex items-center gap-3 mb-8", children: [_jsx("div", { className: "h-12 w-12 rounded-xl bg-gradient-to-br from-primary-500 via-primary-400 to-accent-teal flex items-center justify-center shadow-glass ring-2 ring-white/10", children: _jsx("span", { className: "text-lg font-semibold text-white", children: "\uD83D\uDC8E" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm uppercase tracking-widest text-slate-400 font-medium", children: "Aster Labs" }), _jsx("h1", { className: "text-xl font-bold bg-gradient-to-r from-white via-primary-200 to-accent-teal bg-clip-text text-transparent", children: "Sapphire AI" }), _jsx("p", { className: "text-xs text-slate-500", children: "Multi-Agent Trading" })] })] }), _jsx("nav", { className: "flex-1", children: _jsx("ul", { className: "space-y-1", children: tabs.map((tab) => {
                                const isActive = tab.id === activeTab;
                                return (_jsx("li", { children: _jsxs("button", { type: "button", onClick: () => handleTabSelect(tab.id), className: `group relative flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left transition-all duration-200 overflow-hidden ${isActive
                                            ? 'bg-primary-500/20 text-white shadow-glass scale-[1.02]'
                                            : 'text-slate-400 hover:text-white hover:bg-surface-200/60 hover:scale-[1.01]'}`, children: [_jsx("div", { className: `absolute inset-0 bg-gradient-to-r ${isActive ? 'from-primary-500/10 to-accent-teal/10' : 'from-white/5 to-transparent'} opacity-0 group-hover:opacity-100 transition-opacity duration-200` }), _jsx("span", { className: `text-lg transition-transform duration-200 ${isActive ? 'scale-110' : 'group-hover:scale-105'}`, children: tab.icon }), _jsx("span", { className: "font-medium relative z-10", children: tab.label }), isActive && (_jsx("span", { className: "ml-auto h-2 w-2 rounded-full bg-accent-emerald shadow-glass animate-pulse" })), !isActive && (_jsx("span", { className: "ml-auto opacity-0 group-hover:opacity-100 transition-opacity duration-200 text-xs", children: "\u2192" }))] }) }, tab.id));
                            }) }) }), _jsxs("div", { className: "relative rounded-xl border border-surface-200/40 bg-gradient-to-br from-surface-100/80 to-surface-50/60 p-4 shadow-glass", children: [_jsx("div", { className: "absolute top-0 right-0 h-8 w-8 rounded-full bg-gradient-to-br from-primary-400/20 to-accent-teal/20 blur-sm" }), _jsxs("div", { className: "relative", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx("div", { className: "h-2 w-2 rounded-full bg-emerald-400 animate-pulse shadow-glass" }), _jsx("p", { className: "text-sm font-semibold text-white", children: "Live Capital Engaged" })] }), _jsxs("div", { className: "space-y-1 text-xs text-slate-400", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { children: "Agents:" }), _jsx("span", { className: "text-emerald-400 font-medium", children: "4 Live Models" })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { children: "Margin:" }), _jsx("span", { className: "text-blue-400 font-medium", children: "Full Access" })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { children: "Alerts:" }), _jsx("span", { className: "text-purple-400 font-medium", children: "Telegram Push" })] })] }), _jsx("div", { className: "mt-3 pt-3 border-t border-surface-200/40", children: _jsx("p", { className: "text-xs text-slate-500 text-center", children: "\uD83D\uDC8E Sapphire AI \u2014 Live Desk" }) })] })] })] })] }));
};
export default Sidebar;
