import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
const Sidebar = ({ tabs, activeTab, onSelect, mobileMenuOpen, setMobileMenuOpen }) => {
    const handleTabSelect = (id) => {
        onSelect(id);
        if (setMobileMenuOpen) {
            setMobileMenuOpen(false);
        }
    };
    return (_jsxs(_Fragment, { children: [mobileMenuOpen && (_jsx("div", { className: "fixed inset-0 z-50 bg-black/50 backdrop-blur-sm lg:hidden", onClick: () => setMobileMenuOpen?.(false) })), _jsxs("aside", { className: `fixed lg:static top-0 left-0 z-50 h-full w-64 flex-col gap-6 bg-gradient-to-b from-brand-abyss/95 via-brand-deep/92 to-brand-midnight/95 border-r border-brand-border/70 backdrop-blur-lg p-6 transition-transform duration-300 lg:translate-x-0 ${mobileMenuOpen ? 'translate-x-0' : '-translate-x-full lg:flex'}`, children: [_jsx("div", { className: "absolute top-0 right-0 h-32 w-32 rounded-full bg-gradient-to-br from-accent-sapphire/20 to-accent-emerald/10 blur-2xl" }), _jsx("div", { className: "absolute bottom-0 left-0 h-24 w-24 rounded-full bg-gradient-to-br from-accent-aurora/15 to-accent-sapphire/10 blur-xl" }), _jsxs("div", { className: "relative flex items-center gap-3 mb-8", children: [_jsx("div", { className: "h-12 w-12 rounded-xl bg-gradient-to-br from-accent-sapphire via-accent-emerald to-accent-aurora flex items-center justify-center shadow-sapphire ring-2 ring-brand-border/40", children: _jsx("span", { className: "text-lg font-semibold text-brand-midnight", children: "\uD83D\uDC8E" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm uppercase tracking-widest text-brand-muted font-medium", children: "Sapphire Labs" }), _jsx("h1", { className: "text-xl font-bold bg-gradient-to-r from-brand-ice via-accent-sapphire to-accent-emerald bg-clip-text text-transparent", children: "Sapphire AI" }), _jsx("p", { className: "text-xs text-brand-muted/70", children: "Multi-Agent Trading" })] })] }), _jsxs("nav", { className: "relative flex-1", children: [_jsx("div", { className: "pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-accent-sapphire/25 to-transparent" }), _jsx("ul", { className: "space-y-1", children: tabs.map((tab) => {
                                    const isActive = tab.id === activeTab;
                                    return (_jsx("li", { children: _jsxs("button", { type: "button", onClick: () => handleTabSelect(tab.id), className: `group relative flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left transition-all duration-200 overflow-hidden ${isActive
                                                ? 'text-brand-ice shadow-sapphire scale-[1.02]'
                                                : 'text-brand-muted hover:text-brand-ice hover:scale-[1.01]'}`, children: [_jsx("div", { className: `absolute inset-0 bg-gradient-to-r ${isActive ? 'from-accent-sapphire/25 via-accent-emerald/25 to-transparent' : 'from-brand-border/40 to-transparent'} opacity-0 group-hover:opacity-100 transition-opacity duration-200` }), _jsx("span", { className: `text-lg transition-transform duration-200 ${isActive ? 'scale-110' : 'group-hover:scale-105'}`, children: tab.icon }), _jsx("span", { className: "font-medium relative z-10", children: tab.label }), isActive ? (_jsx("span", { className: "ml-auto h-2 w-2 rounded-full bg-accent-emerald shadow-sapphire animate-pulse" })) : (_jsx("span", { className: "ml-auto opacity-0 group-hover:opacity-100 transition-opacity duration-200 text-xs text-brand-muted/70", children: "\u2192" }))] }) }, tab.id));
                                }) })] }), _jsxs("div", { className: "relative rounded-xl border border-brand-border/60 bg-brand-abyss/80 p-4 shadow-sapphire backdrop-blur-xl", children: [_jsx("div", { className: "absolute top-0 right-0 h-8 w-8 rounded-full bg-gradient-to-br from-accent-sapphire/30 to-accent-emerald/20 blur-sm" }), _jsxs("div", { className: "relative", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx("div", { className: "h-2 w-2 rounded-full bg-accent-emerald animate-pulse shadow-sapphire" }), _jsx("p", { className: "text-sm font-semibold text-brand-ice", children: "Live Capital Engaged" })] }), _jsxs("div", { className: "space-y-1 text-xs text-brand-muted", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { children: "Agents:" }), _jsx("span", { className: "text-accent-sapphire font-medium", children: "4 Live Models" })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { children: "Margin:" }), _jsx("span", { className: "text-accent-emerald font-medium", children: "Full Access" })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { children: "Alerts:" }), _jsx("span", { className: "text-accent-aurora font-medium", children: "Telegram Push" })] })] }), _jsx("div", { className: "mt-3 pt-3 border-t border-brand-border/50", children: _jsx("p", { className: "text-xs text-brand-muted text-center", children: "\uD83D\uDC8E Sapphire AI \u2014 Live Desk" }) })] })] })] })] }));
};
export default Sidebar;
