import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const TopBar = ({ onRefresh, lastUpdated, healthRunning, mobileMenuOpen, setMobileMenuOpen, onBackToHome, connectionStatus = 'connecting', error, autoRefreshEnabled = true, onToggleAutoRefresh }) => {
    const statusLabel = healthRunning ? 'Live' : 'Paused';
    const statusColor = healthRunning ? 'bg-accent-emerald/85 text-brand-midnight' : 'bg-warning-amber/85 text-brand-midnight';
    const connectionColor = connectionStatus === 'connected' ? 'text-accent-emerald' :
        connectionStatus === 'connecting' ? 'text-accent-sapphire' : 'text-error';
    const connectionIcon = connectionStatus === 'connected' ? '🟢' :
        connectionStatus === 'connecting' ? '🟡' : '🔴';
    return (_jsx("header", { className: "sticky top-0 z-40 border-b border-brand-border/70 bg-brand-abyss/80 backdrop-blur-lg", children: _jsxs("div", { className: "mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-10", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs uppercase tracking-[0.35em] text-accent-sapphire/80", children: "Sapphire Command Verse" }), _jsx("h2", { className: "mt-1 text-3xl font-semibold text-brand-ice", children: "Hyperdrive Trading Nexus" }), _jsx("p", { className: "mt-0.5 text-sm text-brand-muted/80", children: "Solo-built control tower orchestrating GCP-native agents, live capital, and community intelligence." })] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("div", { className: "hidden text-right sm:block", children: [_jsx("p", { className: "text-xs uppercase tracking-wide text-brand-muted/70", children: "Last Sync" }), _jsx("p", { className: "text-sm font-medium text-brand-ice", children: lastUpdated ? new Date(lastUpdated).toLocaleTimeString() : '—' }), _jsxs("div", { className: "flex items-center gap-2 mt-1", children: [_jsx("span", { className: `text-xs ${connectionColor}`, children: connectionIcon }), _jsx("span", { className: "text-xs uppercase tracking-wide text-brand-muted/70", children: connectionStatus })] }), error && (_jsxs("div", { className: "mt-1 text-xs text-error/80 max-w-xs truncate", title: error, children: ["\u26A0\uFE0F ", error] }))] }), _jsxs("span", { className: `inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-medium ${statusColor}`, children: [_jsx("span", { className: "h-2 w-2 rounded-full bg-brand-midnight" }), statusLabel] }), onBackToHome && (_jsxs("button", { type: "button", onClick: onBackToHome, className: "group relative overflow-hidden rounded-full border border-brand-border/60 bg-gradient-to-r from-accent-sapphire/90 to-accent-emerald/90 px-4 py-2 text-sm font-medium text-brand-midnight shadow-sapphire transition-all duration-200 hover:scale-105 active:scale-95", children: [_jsx("span", { className: "mr-2", children: "\uD83C\uDFE0" }), "Home", _jsx("span", { className: "absolute inset-0 rounded-full bg-brand-ice/20 opacity-0 group-active:opacity-100 transition-opacity duration-100" })] })), onToggleAutoRefresh && (_jsxs("button", { type: "button", onClick: onToggleAutoRefresh, className: `group relative overflow-hidden rounded-full px-4 py-2 text-sm font-medium shadow-sapphire transition-all duration-200 hover:scale-105 active:scale-95 ${autoRefreshEnabled
                                ? 'bg-accent-emerald/80 text-brand-midnight hover:bg-accent-emerald'
                                : 'border border-brand-border/60 bg-brand-abyss/80 text-brand-ice hover:bg-brand-abyss/90'}`, title: autoRefreshEnabled ? 'Disable auto-refresh' : 'Enable auto-refresh', children: [_jsx("span", { className: "mr-2", children: autoRefreshEnabled ? '⏸️' : '▶️' }), "Auto", _jsx("span", { className: "absolute inset-0 -z-10 bg-gradient-to-r from-accent-sapphire/40 to-transparent opacity-0 transition-opacity duration-200 group-hover:opacity-100" }), _jsx("span", { className: "absolute inset-0 rounded-full bg-brand-ice/10 opacity-0 group-active:opacity-100 transition-opacity duration-100" })] })), _jsxs("button", { type: "button", onClick: onRefresh, className: "group relative overflow-hidden rounded-full bg-accent-sapphire/85 px-4 py-2 text-sm font-medium text-brand-midnight shadow-sapphire transition-all duration-200 hover:bg-accent-sapphire hover:scale-105 active:scale-95", title: "Refresh data (Ctrl+R)", children: [_jsx("span", { className: "mr-2 transition-transform duration-200 group-hover:rotate-180", children: "\uD83D\uDD04" }), "Refresh", _jsx("span", { className: "absolute inset-0 -z-10 bg-gradient-to-r from-accent-emerald/50 to-transparent opacity-0 transition-opacity duration-200 group-hover:opacity-100" }), _jsx("span", { className: "absolute inset-0 rounded-full bg-brand-ice/10 opacity-0 group-active:opacity-100 transition-opacity duration-100" })] }), setMobileMenuOpen && (_jsx("button", { type: "button", onClick: () => setMobileMenuOpen(!mobileMenuOpen), className: "lg:hidden p-2 rounded-lg text-brand-muted hover:text-brand-ice hover:bg-brand-abyss/70 transition-colors duration-200", children: _jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: mobileMenuOpen ? "M6 18L18 6M6 6l12 12" : "M4 6h16M4 12h16M4 18h16" }) }) }))] })] }) }));
};
export default TopBar;
