import { type FirebaseApp } from 'firebase/app';
import { GoogleAuthProvider, FacebookAuthProvider, OAuthProvider, EmailAuthProvider, type Auth } from 'firebase/auth';
import { type Firestore } from 'firebase/firestore';
declare let app: FirebaseApp | null;
declare let auth: Auth | null;
declare let googleProvider: GoogleAuthProvider | null;
declare let facebookProvider: FacebookAuthProvider | null;
declare let appleProvider: OAuthProvider | null;
declare let emailProvider: EmailAuthProvider | null;
declare let firestore: Firestore | null;
export declare const firebaseEnabled: boolean;
export declare const firestoreEnabled: boolean;
export declare const firebaseInitError: string | null;
export { auth, googleProvider, facebookProvider, appleProvider, emailProvider, firestore };
export default app;
