substitutions:
  _IMAGE_NAME: fingpt-trader
  _BASE_IMAGE: pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'BASE_IMAGE=${_BASE_IMAGE}'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/vertex-ai/${_IMAGE_NAME}:$BUILD_ID'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/vertex-ai/${_IMAGE_NAME}:latest'
      - '-f'
      - 'models/fingpt/Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/vertex-ai/${_IMAGE_NAME}:$BUILD_ID'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/vertex-ai/${_IMAGE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_32'

timeout: '1800s'
